import { MapStyleConfig, MapStylePreset } from './map-types';

export const mapStyles: Record<MapStylePreset, MapStyleConfig> = {
  'dark-network': {
    name: 'dark-network',
    label: 'Dark Network',
    backgroundColor: '#0A0A12',
    landFill: '#0F1B2D',
    landStroke: '#1A3A5C',
    landStrokeWidth: 0.5,
    oceanFill: '#0A0A12',
    borderColor: '#1A3A5C',
    borderWidth: 0.5,
    markerDefaultColor: '#00D4FF',
    connectionDefaultColor: '#00D4FF',
    labelColor: '#C0E8FF',
    labelFont: "'Inter', system-ui, sans-serif",
    titleColor: '#FFFFFF',
    titleFont: "'Inter', system-ui, sans-serif",
    graticuleColor: '#0D1A2A',
    graticuleOpacity: 0.4,
    glowEffect: true,
    dotPattern: true,
  },

  'light-clean': {
    name: 'light-clean',
    label: 'Light Clean',
    backgroundColor: '#FFFFFF',
    landFill: '#E8ECF0',
    landStroke: '#C8D0D8',
    landStrokeWidth: 0.5,
    oceanFill: '#FFFFFF',
    borderColor: '#B0B8C4',
    borderWidth: 0.5,
    markerDefaultColor: '#2563EB',
    connectionDefaultColor: '#2563EB',
    labelColor: '#1A1A2E',
    labelFont: "'Inter', system-ui, sans-serif",
    titleColor: '#0F172A',
    titleFont: "'Inter', system-ui, sans-serif",
  },

  'satellite-glow': {
    name: 'satellite-glow',
    label: 'Satellite Glow',
    backgroundColor: '#050510',
    landFill: '#1A2332',
    landStroke: '#2A4A6A',
    landStrokeWidth: 0.8,
    oceanFill: '#050510',
    borderColor: '#2A4A6A',
    borderWidth: 0.4,
    markerDefaultColor: '#00FF88',
    connectionDefaultColor: '#00FF88',
    labelColor: '#A0FFD0',
    labelFont: "'Courier New', monospace",
    titleColor: '#00FF88',
    titleFont: "'Courier New', monospace",
    graticuleColor: '#0A1520',
    graticuleOpacity: 0.3,
    glowEffect: true,
  },

  blueprint: {
    name: 'blueprint',
    label: 'Blueprint',
    backgroundColor: '#0A1628',
    landFill: '#0E1E38',
    landStroke: '#2A5A8A',
    landStrokeWidth: 0.8,
    oceanFill: '#0A1628',
    borderColor: '#2A5A8A',
    borderWidth: 0.6,
    markerDefaultColor: '#4A9EFF',
    connectionDefaultColor: '#4A9EFF',
    labelColor: '#7AB8FF',
    labelFont: "'Courier New', monospace",
    titleColor: '#FFFFFF',
    titleFont: "'Courier New', monospace",
    graticuleColor: '#162A44',
    graticuleOpacity: 0.5,
  },

  minimal: {
    name: 'minimal',
    label: 'Minimal',
    backgroundColor: '#FAFAFA',
    landFill: '#F0F0F0',
    landStroke: '#D0D0D0',
    landStrokeWidth: 0.3,
    oceanFill: '#FAFAFA',
    borderColor: '#C0C0C0',
    borderWidth: 0.3,
    markerDefaultColor: '#171717',
    connectionDefaultColor: '#404040',
    labelColor: '#171717',
    labelFont: "'SF Pro Display', 'Helvetica Neue', sans-serif",
    titleColor: '#171717',
    titleFont: "'SF Pro Display', 'Helvetica Neue', sans-serif",
  },

  neon: {
    name: 'neon',
    label: 'Neon',
    backgroundColor: '#0D0D0D',
    landFill: '#141418',
    landStroke: '#FF00FF',
    landStrokeWidth: 0.6,
    oceanFill: '#0D0D0D',
    borderColor: '#FF00FF',
    borderWidth: 0.4,
    markerDefaultColor: '#00FFFF',
    connectionDefaultColor: '#FF00FF',
    labelColor: '#FFFFFF',
    labelFont: "'Inter', system-ui, sans-serif",
    titleColor: '#FF00FF',
    titleFont: "'Inter', system-ui, sans-serif",
    graticuleColor: '#1A1A1A',
    graticuleOpacity: 0.4,
    glowEffect: true,
  },
};

export function getMapStyle(name: MapStylePreset, customOverrides?: Partial<MapStyleConfig>): MapStyleConfig {
  const base = mapStyles[name] || mapStyles['dark-network'];
  if (!customOverrides) return base;
  return { ...base, ...customOverrides };
}
