import { TimelineItem, TimelineSettings } from './types';

export const sampleSettings: TimelineSettings = {
  view: 'quarterly',
  theme: 'corporate',
  title: 'Product Roadmap 2025',
  subtitle: 'Engineering & Design',
  startDate: '2025-01-01',
  endDate: '2026-03-31',
  showGrid: true,
  showLabels: true,
  showTodayMarker: true,
  showProgress: false,
  rowLabels: ['Strategy', 'Design', 'Development', 'Launch'],
  eventLines: [],
};

export const sampleItems: TimelineItem[] = [
  // Row 0 - Strategy
  {
    id: 'strat-1',
    type: 'phase',
    label: 'Market Research',
    description: 'Competitive analysis and user interviews',
    startDate: '2025-01-01',
    endDate: '2025-03-15',
    row: 0,
    category: 'strategy',
  },
  {
    id: 'strat-2',
    type: 'milestone',
    label: 'Strategy Approved',
    startDate: '2025-03-31',
    row: 0,
    category: 'strategy',
  },
  {
    id: 'strat-3',
    type: 'phase',
    label: 'Roadmap Planning',
    description: 'Feature prioritization and resource allocation',
    startDate: '2025-03-15',
    endDate: '2025-05-31',
    row: 0,
    category: 'strategy',
  },

  // Row 1 - Design
  {
    id: 'des-1',
    type: 'phase',
    label: 'UX Research',
    description: 'User journey mapping and persona development',
    startDate: '2025-02-01',
    endDate: '2025-04-15',
    row: 1,
    category: 'design',
  },
  {
    id: 'des-2',
    type: 'phase',
    label: 'UI Design Sprint',
    description: 'High-fidelity mockups and design system updates',
    startDate: '2025-04-15',
    endDate: '2025-07-31',
    row: 1,
    category: 'design',
  },
  {
    id: 'des-3',
    type: 'milestone',
    label: 'Design Handoff',
    startDate: '2025-08-01',
    row: 1,
    category: 'design',
  },

  // Row 2 - Development
  {
    id: 'dev-1',
    type: 'phase',
    label: 'Backend Architecture',
    description: 'API design, database schema, infrastructure setup',
    startDate: '2025-04-01',
    endDate: '2025-06-30',
    row: 2,
    category: 'development',
  },
  {
    id: 'dev-2',
    type: 'phase',
    label: 'Frontend Development',
    description: 'Component library, pages, and integrations',
    startDate: '2025-06-15',
    endDate: '2025-10-31',
    row: 2,
    category: 'development',
  },
  {
    id: 'dev-3',
    type: 'phase',
    label: 'Testing & QA',
    description: 'Unit tests, integration tests, and UAT',
    startDate: '2025-09-01',
    endDate: '2025-12-15',
    row: 2,
    category: 'development',
  },

  // Row 3 - Launch
  {
    id: 'launch-1',
    type: 'phase',
    label: 'Beta Program',
    description: 'Internal beta with select customers',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    row: 3,
    category: 'launch',
  },
  {
    id: 'launch-2',
    type: 'milestone',
    label: 'Public Launch',
    startDate: '2026-01-15',
    row: 3,
    category: 'launch',
  },
  {
    id: 'launch-3',
    type: 'phase',
    label: 'Post-Launch Iteration',
    description: 'Bug fixes, feature enhancements, monitoring',
    startDate: '2026-01-15',
    endDate: '2026-03-31',
    row: 3,
    category: 'launch',
  },
];

export const templates = {
  'product-roadmap': {
    name: 'Product Roadmap',
    settings: sampleSettings,
    items: sampleItems,
  },
  'sprint-plan': {
    name: 'Sprint Plan',
    settings: {
      ...sampleSettings,
      view: 'monthly' as const,
      title: 'Sprint Plan - Q1 2025',
      subtitle: 'Team Alpha',
      startDate: '2025-01-01',
      endDate: '2025-03-31',
      rowLabels: ['Frontend', 'Backend', 'DevOps', 'QA'],
    },
    items: [
      { id: 'sp-1', type: 'phase' as const, label: 'Auth Module', startDate: '2025-01-06', endDate: '2025-01-24', row: 0, category: 'frontend' },
      { id: 'sp-2', type: 'phase' as const, label: 'Dashboard UI', startDate: '2025-01-27', endDate: '2025-02-14', row: 0, category: 'frontend' },
      { id: 'sp-3', type: 'phase' as const, label: 'API Gateway', startDate: '2025-01-06', endDate: '2025-02-07', row: 1, category: 'backend' },
      { id: 'sp-4', type: 'phase' as const, label: 'Data Pipeline', startDate: '2025-02-10', endDate: '2025-03-07', row: 1, category: 'backend' },
      { id: 'sp-5', type: 'phase' as const, label: 'CI/CD Setup', startDate: '2025-01-06', endDate: '2025-01-31', row: 2, category: 'devops' },
      { id: 'sp-6', type: 'milestone' as const, label: 'Infra Ready', startDate: '2025-02-01', row: 2, category: 'devops' },
      { id: 'sp-7', type: 'phase' as const, label: 'Test Suite', startDate: '2025-02-03', endDate: '2025-03-14', row: 3, category: 'qa' },
      { id: 'sp-8', type: 'milestone' as const, label: 'Release v1.0', startDate: '2025-03-28', row: 3, category: 'qa' },
    ],
  },
  'project-timeline': {
    name: 'Project Timeline',
    settings: {
      ...sampleSettings,
      view: 'yearly' as const,
      title: 'Digital Transformation',
      subtitle: '3-Year Strategic Initiative',
      startDate: '2025-01-01',
      endDate: '2027-12-31',
      rowLabels: ['Phase 1: Foundation', 'Phase 2: Migration', 'Phase 3: Innovation'],
    },
    items: [
      { id: 'pt-1', type: 'phase' as const, label: 'Assessment & Planning', startDate: '2025-01-01', endDate: '2025-06-30', row: 0, category: 'foundation' },
      { id: 'pt-2', type: 'phase' as const, label: 'Infrastructure Modernization', startDate: '2025-04-01', endDate: '2025-12-31', row: 0, category: 'foundation' },
      { id: 'pt-3', type: 'milestone' as const, label: 'Foundation Complete', startDate: '2025-12-31', row: 0, category: 'foundation' },
      { id: 'pt-4', type: 'phase' as const, label: 'Data Migration', startDate: '2026-01-01', endDate: '2026-08-31', row: 1, category: 'migration' },
      { id: 'pt-5', type: 'phase' as const, label: 'System Integration', startDate: '2026-06-01', endDate: '2026-12-31', row: 1, category: 'migration' },
      { id: 'pt-6', type: 'milestone' as const, label: 'Migration Complete', startDate: '2026-12-31', row: 1, category: 'migration' },
      { id: 'pt-7', type: 'phase' as const, label: 'AI/ML Implementation', startDate: '2027-01-01', endDate: '2027-09-30', row: 2, category: 'innovation' },
      { id: 'pt-8', type: 'phase' as const, label: 'Optimization & Scale', startDate: '2027-07-01', endDate: '2027-12-31', row: 2, category: 'innovation' },
      { id: 'pt-9', type: 'milestone' as const, label: 'Transformation Complete', startDate: '2027-12-31', row: 2, category: 'innovation' },
    ],
  },
};
