import { ThemeConfig, ThemeEffects } from './types';

const noEffects: ThemeEffects = {};

export const themes: Record<string, ThemeConfig> = {
  // ══════════════════════════════════════════
  // CLASSIC THEMES
  // ══════════════════════════════════════════
  corporate: {
    name: 'corporate',
    label: 'Corporate',
    description: 'Clean blues and grays, boardroom-ready',
    category: 'classic',
    colors: {
      background: '#FFFFFF',
      surface: '#F8F9FA',
      surfaceHover: '#E9ECEF',
      border: '#DEE2E6',
      text: '#212529',
      textSecondary: '#495057',
      textMuted: '#868E96',
      primary: '#1864AB',
      primaryLight: '#D0EBFF',
      accent: '#087F5B',
      gridLine: '#E9ECEF',
      gridText: '#868E96',
      headerBg: '#1864AB',
      headerText: '#FFFFFF',
      categories: ['#1864AB', '#087F5B', '#862E9C', '#C92A2A', '#E67700', '#2B8A3E', '#364FC7', '#5C5F66'],
    },
    effects: noEffects,
    borderRadius: '4px',
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    headingFont: "'Georgia', 'Times New Roman', serif",
    itemHeight: 32,
    itemGap: 8,
    barStyle: 'rounded',
    milestoneShape: 'diamond',
  },

  modern: {
    name: 'modern',
    label: 'Modern',
    description: 'Dark mode with vibrant accents',
    category: 'classic',
    colors: {
      background: '#0A0A0F',
      surface: '#16161D',
      surfaceHover: '#1E1E28',
      border: '#2A2A35',
      text: '#EEEEF0',
      textSecondary: '#A0A0B0',
      textMuted: '#606070',
      primary: '#6C5CE7',
      primaryLight: '#2D2850',
      accent: '#00D2D3',
      gridLine: '#1E1E28',
      gridText: '#606070',
      headerBg: '#16161D',
      headerText: '#EEEEF0',
      categories: ['#6C5CE7', '#00D2D3', '#FD79A8', '#FDCB6E', '#55EFC4', '#74B9FF', '#FF6B6B', '#A29BFE'],
    },
    effects: noEffects,
    borderRadius: '8px',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    headingFont: "'Inter', system-ui, -apple-system, sans-serif",
    itemHeight: 34,
    itemGap: 10,
    barStyle: 'pill',
    milestoneShape: 'circle',
  },

  minimal: {
    name: 'minimal',
    label: 'Minimal',
    description: 'Monochrome, generous whitespace',
    category: 'classic',
    colors: {
      background: '#FFFFFF',
      surface: '#FAFAFA',
      surfaceHover: '#F5F5F5',
      border: '#E5E5E5',
      text: '#171717',
      textSecondary: '#525252',
      textMuted: '#A3A3A3',
      primary: '#171717',
      primaryLight: '#F5F5F5',
      accent: '#525252',
      gridLine: '#F0F0F0',
      gridText: '#A3A3A3',
      headerBg: '#FAFAFA',
      headerText: '#171717',
      categories: ['#171717', '#525252', '#737373', '#404040', '#262626', '#3F3F46', '#52525B', '#71717A'],
    },
    effects: noEffects,
    borderRadius: '2px',
    fontFamily: "'SF Pro Display', 'Helvetica Neue', system-ui, sans-serif",
    headingFont: "'SF Pro Display', 'Helvetica Neue', system-ui, sans-serif",
    itemHeight: 28,
    itemGap: 12,
    barStyle: 'sharp',
    milestoneShape: 'circle',
  },

  colorful: {
    name: 'colorful',
    label: 'Colorful',
    description: 'Bright and expressive, Notion-inspired',
    category: 'classic',
    colors: {
      background: '#FFFDF7',
      surface: '#FFF8EE',
      surfaceHover: '#FFF0DB',
      border: '#F0E4D1',
      text: '#37352F',
      textSecondary: '#6B6B6B',
      textMuted: '#9B9A97',
      primary: '#E16259',
      primaryLight: '#FDECEA',
      accent: '#4EA4B7',
      gridLine: '#F0E4D1',
      gridText: '#9B9A97',
      headerBg: '#FFFDF7',
      headerText: '#37352F',
      categories: ['#E16259', '#4EA4B7', '#D9A84E', '#6BBF6B', '#9B6BBF', '#E88B5A', '#5A8FE8', '#E85A8F'],
    },
    effects: noEffects,
    borderRadius: '6px',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    headingFont: "'Inter', system-ui, -apple-system, sans-serif",
    itemHeight: 34,
    itemGap: 10,
    barStyle: 'rounded',
    milestoneShape: 'diamond',
  },

  // ══════════════════════════════════════════
  // STYLISTIC THEMES
  // ══════════════════════════════════════════
  scifi: {
    name: 'scifi',
    label: 'Sci-Fi',
    description: 'Cyberpunk HUD with scanlines and tech feel',
    category: 'stylistic',
    colors: {
      background: '#050510',
      surface: '#0A0A1A',
      surfaceHover: '#101025',
      border: '#1A1A3A',
      text: '#00FFCC',
      textSecondary: '#00AA88',
      textMuted: '#336655',
      primary: '#00FFCC',
      primaryLight: '#0A2A20',
      accent: '#FF003C',
      gridLine: '#0D1A2A',
      gridText: '#336655',
      headerBg: '#050510',
      headerText: '#00FFCC',
      categories: ['#00FFCC', '#FF003C', '#00AAFF', '#FFAA00', '#CC00FF', '#00FF66', '#FF6600', '#6600FF'],
    },
    effects: {
      barGradient: true,
      barGradientDirection: 'horizontal',
      barGlow: true,
      barGlowColor: '#00FFCC',
      barGlowRadius: 5,
      barOpacity: 0.9,
      barStroke: true,
      barStrokeColor: '#00FFCC',
      barStrokeWidth: 1,
      bgPattern: 'scanlines',
      bgPatternColor: '#00FFCC',
      bgPatternOpacity: 0.03,
      gridGlow: true,
      gridStyle: 'solid',
      textGlow: true,
      textGlowColor: '#00FFCC',
      milestoneGlow: true,
    },
    borderRadius: '2px',
    fontFamily: "'Courier New', 'Consolas', monospace",
    headingFont: "'Courier New', 'Consolas', monospace",
    itemHeight: 30,
    itemGap: 10,
    barStyle: 'sharp',
    milestoneShape: 'diamond',
  },

  glass: {
    name: 'glass',
    label: 'Glass',
    description: 'Frosted glass with transparency and blur',
    category: 'stylistic',
    colors: {
      background: '#1A1A2E',
      surface: '#16213E',
      surfaceHover: '#1A2744',
      border: 'rgba(255,255,255,0.12)',
      text: '#FFFFFF',
      textSecondary: 'rgba(255,255,255,0.7)',
      textMuted: 'rgba(255,255,255,0.4)',
      primary: '#667EEA',
      primaryLight: 'rgba(102,126,234,0.2)',
      accent: '#764BA2',
      gridLine: 'rgba(255,255,255,0.06)',
      gridText: 'rgba(255,255,255,0.3)',
      headerBg: 'rgba(255,255,255,0.05)',
      headerText: '#FFFFFF',
      categories: ['#667EEA', '#764BA2', '#F093FB', '#4FACFE', '#00F2FE', '#43E97B', '#FA709A', '#FEE140'],
    },
    effects: {
      barGradient: true,
      barGradientDirection: 'horizontal',
      barGlow: true,
      barGlowColor: 'rgba(255,255,255,0.15)',
      barGlowRadius: 6,
      barOpacity: 0.55,
      barStroke: true,
      barStrokeColor: 'rgba(255,255,255,0.25)',
      barStrokeWidth: 1,
      barInnerShadow: true,
      bgPattern: 'none',
      gridStyle: 'solid',
      milestoneGlow: true,
      useBlur: true,
    },
    borderRadius: '12px',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    headingFont: "'Inter', system-ui, -apple-system, sans-serif",
    itemHeight: 36,
    itemGap: 10,
    barStyle: 'pill',
    milestoneShape: 'circle',
  },

  liquid: {
    name: 'liquid',
    label: 'Liquid',
    description: 'Organic, fluid shapes with soft gradients',
    category: 'stylistic',
    colors: {
      background: '#F0E6FF',
      surface: '#E8DAFF',
      surfaceHover: '#DBC8FF',
      border: '#C9AAFF',
      text: '#2D1B69',
      textSecondary: '#5B3E9E',
      textMuted: '#8B6EC0',
      primary: '#7C3AED',
      primaryLight: '#EDE0FF',
      accent: '#EC4899',
      gridLine: '#D4BFFF',
      gridText: '#8B6EC0',
      headerBg: '#F0E6FF',
      headerText: '#2D1B69',
      categories: ['#7C3AED', '#EC4899', '#06B6D4', '#F59E0B', '#10B981', '#EF4444', '#8B5CF6', '#3B82F6'],
    },
    effects: {
      barGradient: true,
      barGradientDirection: 'vertical',
      barGlow: true,
      barGlowColor: 'rgba(124,58,237,0.3)',
      barGlowRadius: 5,
      barOpacity: 0.85,
      bgPattern: 'dots',
      bgPatternColor: '#7C3AED',
      bgPatternOpacity: 0.06,
      gridStyle: 'dotted',
    },
    borderRadius: '20px',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    headingFont: "'Inter', system-ui, -apple-system, sans-serif",
    itemHeight: 36,
    itemGap: 12,
    barStyle: 'pill',
    milestoneShape: 'circle',
  },

  y2k: {
    name: 'y2k',
    label: 'Y2K',
    description: 'Retro 2000s aesthetic with chrome and gradients',
    category: 'stylistic',
    colors: {
      background: '#FFE4F3',
      surface: '#FFD1EC',
      surfaceHover: '#FFC0E5',
      border: '#FF99D6',
      text: '#660044',
      textSecondary: '#990066',
      textMuted: '#CC3399',
      primary: '#FF00AA',
      primaryLight: '#FFD1EC',
      accent: '#00CCFF',
      gridLine: '#FFB3E0',
      gridText: '#CC3399',
      headerBg: '#FFE4F3',
      headerText: '#660044',
      categories: ['#FF00AA', '#00CCFF', '#FFCC00', '#CC00FF', '#00FF99', '#FF6600', '#0066FF', '#FF0066'],
    },
    effects: {
      barGradient: true,
      barGradientDirection: 'vertical',
      barGlow: true,
      barGlowColor: 'rgba(255,0,170,0.3)',
      barGlowRadius: 6,
      barOpacity: 0.95,
      barStroke: true,
      barStrokeColor: '#FFFFFF',
      barStrokeWidth: 2,
      barInnerShadow: true,
      bgPattern: 'stars',
      bgPatternColor: '#FF00AA',
      bgPatternOpacity: 0.08,
      gridStyle: 'dashed',
      textGlow: false,
    },
    borderRadius: '16px',
    fontFamily: "'Trebuchet MS', 'Arial', sans-serif",
    headingFont: "'Trebuchet MS', 'Arial', sans-serif",
    itemHeight: 34,
    itemGap: 10,
    barStyle: 'pill',
    milestoneShape: 'star',
  },

  flat: {
    name: 'flat',
    label: 'Flat',
    description: 'Bold solid colors, no gradients, no shadows',
    category: 'stylistic',
    colors: {
      background: '#FFFFFF',
      surface: '#F1F5F9',
      surfaceHover: '#E2E8F0',
      border: '#CBD5E1',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      primary: '#2563EB',
      primaryLight: '#DBEAFE',
      accent: '#DC2626',
      gridLine: '#E2E8F0',
      gridText: '#94A3B8',
      headerBg: '#F8FAFC',
      headerText: '#0F172A',
      categories: ['#2563EB', '#DC2626', '#059669', '#D97706', '#7C3AED', '#DB2777', '#0891B2', '#4F46E5'],
    },
    effects: {
      barOpacity: 1.0,
      bgPattern: 'none',
      gridStyle: 'solid',
    },
    borderRadius: '0px',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    headingFont: "'Inter', system-ui, -apple-system, sans-serif",
    itemHeight: 32,
    itemGap: 8,
    barStyle: 'sharp',
    milestoneShape: 'square',
  },

  neon: {
    name: 'neon',
    label: 'Neon Glow',
    description: 'Electric neon colors on deep dark background',
    category: 'stylistic',
    colors: {
      background: '#0D0D0D',
      surface: '#141414',
      surfaceHover: '#1A1A1A',
      border: '#2A2A2A',
      text: '#FFFFFF',
      textSecondary: '#BBBBBB',
      textMuted: '#666666',
      primary: '#FF00FF',
      primaryLight: '#2A0A2A',
      accent: '#00FFFF',
      gridLine: '#1A1A1A',
      gridText: '#555555',
      headerBg: '#0D0D0D',
      headerText: '#FFFFFF',
      categories: ['#FF00FF', '#00FFFF', '#FF3366', '#33FF66', '#FFFF00', '#FF6600', '#6633FF', '#00FF99'],
    },
    effects: {
      barGradient: true,
      barGradientDirection: 'horizontal',
      barGlow: true,
      barGlowColor: '#FF00FF',
      barGlowRadius: 7,
      barOpacity: 0.9,
      barStroke: true,
      barStrokeColor: '#FFFFFF',
      barStrokeWidth: 0.5,
      bgPattern: 'grid',
      bgPatternColor: '#FF00FF',
      bgPatternOpacity: 0.04,
      gridGlow: true,
      gridStyle: 'solid',
      textGlow: true,
      textGlowColor: '#FF00FF',
      milestoneGlow: true,
      milestonePulse: true,
    },
    borderRadius: '6px',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    headingFont: "'Inter', system-ui, -apple-system, sans-serif",
    itemHeight: 32,
    itemGap: 10,
    barStyle: 'rounded',
    milestoneShape: 'diamond',
  },
  soulius: {
    name: 'soulius',
    label: 'Soulius Minimalism',
    description: 'Frosted glass bars with vivid inner color accents',
    category: 'stylistic',
    colors: {
      background: '#F7F8FA',
      surface: '#FFFFFF',
      surfaceHover: '#F0F1F3',
      border: '#E4E6EB',
      text: '#1A1A2E',
      textSecondary: '#4A4A5A',
      textMuted: '#9A9AAE',
      primary: '#4A6CF7',
      primaryLight: '#EEF0FF',
      accent: '#E84393',
      gridLine: '#EDEEF2',
      gridText: '#B0B0C0',
      headerBg: '#F7F8FA',
      headerText: '#1A1A2E',
      categories: ['#4A6CF7', '#E84393', '#00B894', '#F39C12', '#6C5CE7', '#E17055', '#0984E3', '#00CEC9'],
    },
    effects: {
      barGradient: true,
      barGradientDirection: 'vertical',
      barGlow: true,
      barGlowColor: 'rgba(74,108,247,0.15)',
      barGlowRadius: 4,
      barOpacity: 1.0,
      barStroke: true,
      barStrokeColor: 'rgba(255,255,255,0.8)',
      barStrokeWidth: 1.5,
      barInnerShadow: false,
      bgPattern: 'none',
      gridStyle: 'solid',
    },
    borderRadius: '10px',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    headingFont: "'Inter', system-ui, -apple-system, sans-serif",
    itemHeight: 34,
    itemGap: 10,
    barStyle: 'pill',
    milestoneShape: 'diamond',
  },
};

// Default custom theme (user can modify)
export const defaultCustomTheme: ThemeConfig = {
  ...themes.corporate,
  name: 'custom',
  label: 'Custom',
  description: 'Your custom theme',
  category: 'classic',
};

export function getTheme(name: string): ThemeConfig {
  return themes[name] || themes.corporate;
}
